### ISSUE TITLE
LCK Challenger does not provide data.

### ISSUE THREAD

**Issue by voidscuttle** [zlypher/lol-events#29]
LCK Challengers has not been working this season. Doesn't provide data.

**Comment by zlypher** [comment]
Thank you for reporting this issue and sorry that I couldn't reply sooner.
Unfortunately the split is already over, but from the history it looks like the Events should have been there. I will keep an eye out for this issue next split. Closing this issue for now.

**Comment by xusiai** [comment]
@zlypher Commenting here instead of opening another issue. The LCKCL feed does not seem to provide data as of now. The season starts next week but no events are added to the calendar (whereas LCK/LPL/LEC etc do have their events added). 

Thanks for this project by the way; it provides a lot of value to me.
