### ISSUE TITLE
Worlds Qualifying Series missing

### ISSUE THREAD

**Issue by tobyjzstay** [zlypher/lol-events#30]
PandaScore doesn't seem to have the Worlds Qualifying Series upon getting leagues.

Worlds Qualifying Series is listed under getting tournaments.

```
https://api.pandascore.co/lol/tournaments?filter[name]=Qualifying Series
```

This appears to be because getting leagues doesn't have Worlds 2023 events yet and Worlds Qualifying Series is part of the same league ID as Worlds. Perhaps fetching the following could be used in conjuction with leagues to handle these cases.

```
https://api.pandascore.co/lol/matches
```

```
https://api.pandascore.co/lol/tournaments
```

**Comment by zlypher** [comment]
Thank you very much for reporting this! I think that this is a great idea! I'll try to get to it this week.

**Comment by zlypher** [comment]
Okay, so it looks like the Worlds Qualifying Series is only a single Bo5 between BDS and GG. This one should be available in the regular "Worlds" calender under https://zlypher.github.io/lol-events/cal/league-of-legends-world-championship.ical
Since yesterday it also includes the Playin games. So from what I can tell the Worlds calender now should show all games for Worlds + Qualifier.
